version: "3"
services:
  elk:
    image: sebp/elk:7.11.2
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.12.0
    depends_on:
      - elk
    volumes:
    - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro
    - C:/Softwareentwicklung/Workspaces/IntelliJ/Cloud Example Tracing/logs/:/var/log/app/

#  filebeat: # Use this to collect data from services running inside Docker (more difficult to realize when running on Windows)
#    image: docker.elastic.co/beats/filebeat:7.12.0
#    user: root # We need to ensure that filebeat can access the given volumes which the default user cannot
#    depends_on:
#      - elk
#    volumes:
#      - ./filebeat.yaml:/usr/share/filebeat/filebeat.yml:ro
#      - C:/ProgramData/Docker:/var/lib/docker:ro # Required to access Docker log files
#      - /var/run/docker.sock:/var/run/docker.sock # Required to retrieve additional information from Docker daemon

  jaeger:
    image: jaegertracing/all-in-one:1.22
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

