filebeat.inputs:

#  - type: container # This type enables parsing of Container logs
#    enabled: false
#    paths:
#      - '/var/lib/docker/containers/*/*.log'
#    processors:
#    - add_docker_metadata: ~ # Enrich Docker logs with useful metadata
#    - decode_json_fields: # Parse application logs (stdout) as JSON encoded data
#        fields: [ "message" ]
#        target: "json"
#        overwrite_keys: true

  - type: log
    enabled: true
    paths:
      - '/var/log/app/*.log'
    close_inactive: 1m
    scan_frequency: 10s
    processors:
      - decode_json_fields: # Parse application logs (stdout) as JSON encoded data
          fields: [ "message" ]
          target: "json"
          add_error_key: true
          overwrite_keys: true
      - timestamp:
          field: "json.@timestamp"
          ignore_missing: false
          ignore_failure: false
          layouts:
            - '2006-01-02T15:04:05.999-07:00'
          test:
            - '2021-04-19T16:57:58.717+02:00'
            - '2021-04-19T16:58:26.268+02:00'

output.elasticsearch:
  hosts: [ "elk:9200" ]
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}" # Create an Elastic index on a daily base (makes it easier to remove old logs)

# Configuration related to FileBeat logs
logging.json: true
logging.level: info
logging.metrics.enabled: false
