spring:
  profiles:
    active: default
  application:
    name: service-1
  version: '@project.version@'
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    opentracing:
      enabled: true

server:
  port: 8080

downstream:
  service:
    url: http://localhost:8081/api/hello
