spring:
  profiles:
    active: default
  application:
    name: service-3
  version: '@project.version@'
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    opentracing:
      enabled: true

server:
  port: 8082

downstream:
  service:
    url:
